
[wokwi]
version = 1
firmware = '.pio/build/lolin32/firmware.bin'
elf = '.pio/build/lolin32/firmware.elf'


[wifi]
ssid = "WOKWI-GUEST"
password = ""

[[net.forward]]
from = "localhost:8180"
to = "target:80"